# Generated by Django 4.1.7 on 2023-04-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LRN', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=40)),
            ],
        ),
    ]
