# Generated by Django 4.1.7 on 2023-04-20 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterstation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=40)),
                ('Price', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=40)),
                ('Name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='UserPurchase',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=40)),
                ('Quantity', models.CharField(max_length=40)),
                ('Total', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='UserPurchaseHistory',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=40)),
                ('Quantity', models.CharField(max_length=40)),
                ('Total', models.CharField(max_length=40)),
                ('Status', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
